#include "http_handler.h"
#include <iostream>
#include <chrono>
#include <sstream>
#include <iomanip>

std::string get_html() {
    return std::string(
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "    <meta charset=\"UTF-8\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
        "    <title>Speeqr Audio Conference - Day 2</title>\n"
        "    <style>\n"
        "        * {\n"
        "            margin: 0;\n"
        "            padding: 0;\n"
        "            box-sizing: border-box;\n"
        "        }\n"
        "        body {\n"
        "            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, monospace;\n"
        "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
        "            min-height: 100vh;\n"
        "            padding: 20px;\n"
        "        }\n"
        "        .container {\n"
        "            max-width: 900px;\n"
        "            margin: 0 auto;\n"
        "            background: rgba(255,255,255,0.95);\n"
        "            border-radius: 20px;\n"
        "            padding: 30px;\n"
        "            box-shadow: 0 20px 60px rgba(0,0,0,0.3);\n"
        "        }\n"
        "        h1 {\n"
        "            color: #667eea;\n"
        "            margin-bottom: 10px;\n"
        "            font-size: 2em;\n"
        "        }\n"
        "        .subtitle {\n"
        "            color: #666;\n"
        "            margin-bottom: 20px;\n"
        "            font-size: 0.9em;\n"
        "        }\n"
        "        .status-card {\n"
        "            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n"
        "            color: white;\n"
        "            padding: 15px;\n"
        "            border-radius: 10px;\n"
        "            margin-bottom: 20px;\n"
        "        }\n"
        "        .info-panel {\n"
        "            background: #f0f0f0;\n"
        "            padding: 15px;\n"
        "            border-radius: 10px;\n"
        "            margin-bottom: 20px;\n"
        "            font-family: monospace;\n"
        "            font-size: 12px;\n"
        "        }\n"
        "        .control-group {\n"
        "            margin-bottom: 20px;\n"
        "            display: flex;\n"
        "            gap: 10px;\n"
        "            flex-wrap: wrap;\n"
        "        }\n"
        "        input {\n"
        "            flex: 1;\n"
        "            padding: 12px;\n"
        "            border: 2px solid #ddd;\n"
        "            border-radius: 8px;\n"
        "            font-size: 14px;\n"
        "            font-family: monospace;\n"
        "        }\n"
        "        button {\n"
        "            padding: 12px 24px;\n"
        "            border: none;\n"
        "            border-radius: 8px;\n"
        "            font-size: 14px;\n"
        "            font-weight: bold;\n"
        "            cursor: pointer;\n"
        "            transition: all 0.3s ease;\n"
        "        }\n"
        "        button.join {\n"
        "            background: #4CAF50;\n"
        "            color: white;\n"
        "        }\n"
        "        button.join:hover {\n"
        "            background: #45a049;\n"
        "            transform: translateY(-2px);\n"
        "        }\n"
        "        button.leave {\n"
        "            background: #f44336;\n"
        "            color: white;\n"
        "        }\n"
        "        button.leave:hover {\n"
        "            background: #da190b;\n"
        "            transform: translateY(-2px);\n"
        "        }\n"
        "        button.mute {\n"
        "            background: #ff9800;\n"
        "            color: white;\n"
        "        }\n"
        "        button.mute.active {\n"
        "            background: #f44336;\n"
        "        }\n"
        "        .audio-controls {\n"
        "            background: #e3f2fd;\n"
        "            padding: 15px;\n"
        "            border-radius: 10px;\n"
        "            margin-bottom: 20px;\n"
        "        }\n"
        "        .messages {\n"
        "            background: #fafafa;\n"
        "            border: 1px solid #ddd;\n"
        "            border-radius: 10px;\n"
        "            height: 300px;\n"
        "            overflow-y: auto;\n"
        "            padding: 15px;\n"
        "            font-family: monospace;\n"
        "            font-size: 12px;\n"
        "        }\n"
        "        .message {\n"
        "            padding: 5px;\n"
        "            border-bottom: 1px solid #eee;\n"
        "            color: #333;\n"
        "        }\n"
        "        .message.info {\n"
        "            color: #2196F3;\n"
        "        }\n"
        "        .message.error {\n"
        "            color: #f44336;\n"
        "        }\n"
        "        .message.success {\n"
        "            color: #4CAF50;\n"
        "        }\n"
        "        .stats {\n"
        "            display: grid;\n"
        "            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n"
        "            gap: 10px;\n"
        "            margin-bottom: 20px;\n"
        "        }\n"
        "        .stat-card {\n"
        "            background: white;\n"
        "            padding: 10px;\n"
        "            border-radius: 8px;\n"
        "            border: 1px solid #ddd;\n"
        "            text-align: center;\n"
        "        }\n"
        "        .stat-label {\n"
        "            font-size: 11px;\n"
        "            color: #666;\n"
        "            text-transform: uppercase;\n"
        "        }\n"
        "        .stat-value {\n"
        "            font-size: 20px;\n"
        "            font-weight: bold;\n"
        "            color: #667eea;\n"
        "        }\n"
        "        @keyframes pulse {\n"
        "            0% { opacity: 1; }\n"
        "            50% { opacity: 0.5; }\n"
        "            100% { opacity: 1; }\n"
        "        }\n"
        "        .recording {\n"
        "            animation: pulse 1s infinite;\n"
        "        }\n"
        "    </style>\n"
        "</head>\n"
        "<body>\n"
        "    <div class=\"container\">\n"
        "        <h1>Speeqr Audio Conference</h1>\n"
        "        <div class=\"subtitle\">Day 2: Audio Ingress & Jitter Buffer | C++ Real-Time Server</div>\n"
        "        \n"
        "        <div class=\"status-card\" id=\"statusCard\">\n"
        "            <div id=\"connectionStatus\"> Disconnected</div>\n"
        "            <div id=\"ntpStatus\" style=\"font-size: 12px; margin-top: 5px;\"> Syncing...</div>\n"
        "        </div>\n"
        "        \n"
        "        <div class=\"stats\">\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-label\">NTP Offset</div>\n"
        "                <div class=\"stat-value\" id=\"ntpOffset\">-- ms</div>\n"
        "            </div>\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-label\">Audio Frames Sent</div>\n"
        "                <div class=\"stat-value\" id=\"framesSent\">0</div>\n"
        "            </div>\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-label\">Frames Received</div>\n"
        "                <div class=\"stat-value\" id=\"framesReceived\">0</div>\n"
        "            </div>\n"
        "            <div class=\"stat-card\">\n"
        "                <div class=\"stat-label\">Avg Frame Time</div>\n"
        "                <div class=\"stat-value\" id=\"avgFrameTime\">-- ms</div>\n"
        "            </div>\n"
        "        </div>\n"
        "        \n"
        "        <div class=\"control-group\">\n"
        "            <input type=\"text\" id=\"roomId\" placeholder=\"Room ID\" value=\"Room_A\">\n"
        "            <button class=\"join\" onclick=\"joinRoom()\"> Join Room</button>\n"
        "            <button class=\"leave\" onclick=\"leaveRoom()\"> Leave Room</button>\n"
        "        </div>\n"
        "        \n"
        "        <div class=\"audio-controls\">\n"
        "            <button id=\"muteBtn\" class=\"mute\" onclick=\"toggleMute()\"> Mute</button>\n"
        "            <span id=\"audioStatus\" style=\"margin-left: 10px;\"> Audio: Ready</span>\n"
        "            <span id=\"micLevel\" style=\"margin-left: 10px; font-size: 12px;\"></span>\n"
        "        </div>\n"
        "        \n"
        "        <div class=\"info-panel\">\n"
        "            <strong> Audio Configuration:</strong><br>\n"
        "            Sample Rate: 48kHz | Channels: Mono | Frame Size: 20ms | Format: PCM Int16<br>\n"
        "            Jitter Buffer: 200ms max | Target: 80ms | Auto-adjusting\n"
        "        </div>\n"
        "        \n"
        "        <div id=\"messages\" class=\"messages\">\n"
        "            <div class=\"message info\"> Welcome to Speeqr! Join a room to start.</div>\n"
        "        </div>\n"
        "    </div>\n"
        "    \n"
        "        <script>\n"
"        const AUDIO_CONFIG = {\n"
"            sampleRate: 48000,\n"
"            frameDurationMs: 20,\n"
"            samplesPerFrame: 960\n"
"        };\n"
"        \n"
"        let ws = null;\n"
"        let currentRoom = null;\n"
"        let isExplicitClose = false;\n"
"        let isMuted = false;\n"
"        let audioContext = null;\n"
"        let mediaStream = null;\n"
"        let scriptProcessor = null;\n"
"        let frameCount = 0;\n"
"        let totalFrameTime = 0;\n"
"        let framesReceived = 0;\n"
"        let pendingSamples = [];\n"
"        \n"
"        // Client-side jitter buffer\n"
"        let jitterQueue = [];\n"
"        let isPlaying = false;\n"
"        let nextPlayTime = 0;\n"
"        let targetLatencyMs = 100;\n"
"        let underrunCount = 0;\n"
"        \n"
"        function addToJitterBuffer(samples) {\n"
"            jitterQueue.push({\n"
"                samples: samples,\n"
"                receivedAt: performance.now()\n"
"            });\n"
"            \n"
"            if (!isPlaying && jitterQueue.length >= 3) {\n"
"                startPlayback();\n"
"            }\n"
"        }\n"
"        \n"
"        function startPlayback() {\n"
"            console.log('Starting playback with ' + jitterQueue.length + ' packets');\n"
"            isPlaying = true;\n"
"            nextPlayTime = audioContext.currentTime + 0.05;\n"
"            processJitterQueue();\n"
"        }\n"
"        \n"
"        function processJitterQueue() {\n"
"            if (!isPlaying) return;\n"
"            \n"
"            const now = audioContext.currentTime;\n"
"            \n"
"            if (jitterQueue.length === 0) {\n"
"                underrunCount++;\n"
"                console.warn('Buffer underrun #' + underrunCount);\n"
"                setTimeout(function() { processJitterQueue(); }, 10);\n"
"                return;\n"
"            }\n"
"            \n"
"            const expectedBuffered = targetLatencyMs / 20;\n"
"            if (jitterQueue.length < expectedBuffered - 1 && jitterQueue.length < 15) {\n"
"                setTimeout(function() { processJitterQueue(); }, 5);\n"
"                return;\n"
"            }\n"
"            \n"
"            const packet = jitterQueue.shift();\n"
"            \n"
"            let playTime = nextPlayTime;\n"
"            if (playTime < now - 0.01) {\n"
"                console.log('Behind schedule, catching up');\n"
"                playTime = now + 0.00x5;\n"
"                nextPlayTime = playTime + 0.020;\n"
"            } else {\n"
"                nextPlayTime += 0.020;\n"
"            }\n"
"            \n"
"            playAudioAtTime(packet.samples, playTime);\n"
"            \n"
"            const timeUntilNext = (nextPlayTime - now) * 1000;\n"
"            const waitTime = Math.max(0, Math.min(50, timeUntilNext));\n"
"            setTimeout(function() { processJitterQueue(); }, waitTime);\n"
"        }\n"
"        \n"
"        function playAudioAtTime(samples, playTime) {\n"
"            if (!audioContext || audioContext.state === 'closed') return;\n"
"            \n"
"            framesReceived++;\n"
"            document.getElementById('framesReceived').innerText = framesReceived;\n"
"            \n"
"            const floatSamples = new Float32Array(samples.length);\n"
"            for (let i = 0; i < samples.length; i++) {\n"
"                floatSamples[i] = samples[i] / 32768.0;\n"
"            }\n"
"            \n"
"            const buffer = audioContext.createBuffer(1, samples.length, AUDIO_CONFIG.sampleRate);\n"
"            buffer.copyToChannel(floatSamples, 0);\n"
"            \n"
"            const source = audioContext.createBufferSource();\n"
"            source.buffer = buffer;\n"
"            source.connect(audioContext.destination);\n"
"            source.start(playTime);\n"
"            source.onended = function() { source.disconnect(); };\n"
"        }\n"
"        \n"
"        class NTPClient {\n"
"            constructor() {\n"
"                this.offset = 0;\n"
"                this.rtt = 0;\n"
"                this.lastSync = 0;\n"
"            }\n"
"            \n"
"            async sync() {\n"
"                const T1 = performance.now();\n"
"                try {\n"
"                    const response = await fetch('/time');\n"
"                    const data = await response.json();\n"
"                    const T4 = performance.now();\n"
"                    const serverTime = data.timestamp;\n"
"                    const clientTime = (T1 + T4) / 2;\n"
"                    this.offset = serverTime - clientTime;\n"
"                    this.rtt = T4 - T1;\n"
"                    this.lastSync = Date.now();\n"
"                    document.getElementById('ntpOffset').innerText = this.offset.toFixed(2) + ' ms';\n"
"                    document.getElementById('ntpStatus').innerHTML = ' Synced | RTT: ' + this.rtt.toFixed(2) + 'ms | Offset: ' + this.offset.toFixed(2) + 'ms';\n"
"                    return this.offset;\n"
"                } catch (error) {\n"
"                    console.error('NTP sync failed:', error);\n"
"                    return 0;\n"
"                }\n"
"            }\n"
"            \n"
"            getServerTime() {\n"
"                return performance.now() + this.offset;\n"
"            }\n"
"        }\n"
"        \n"
"        const ntp = new NTPClient();\n"
"        \n"
"        function addMessage(msg, type) {\n"
"            if(!type) type = 'info';\n"
"            const messagesDiv = document.getElementById('messages');\n"
"            const messageDiv = document.createElement('div');\n"
"            messageDiv.className = 'message ' + type;\n"
"            const timestamp = new Date().toLocaleTimeString();\n"
"            messageDiv.innerHTML = '[' + timestamp + '] ' + msg;\n"
"            messagesDiv.appendChild(messageDiv);\n"
"            messageDiv.scrollIntoView({ behavior: 'smooth', block: 'nearest' });\n"
"        }\n"
"        \n"
"        function updateFramesSent() {\n"
"            document.getElementById('framesSent').innerText = frameCount;\n"
"            if (frameCount > 0) {\n"
"                const avgTime = totalFrameTime / frameCount;\n"
"                const avgFrameTimeEl = document.getElementById('avgFrameTime');\n"
"                if (avgFrameTimeEl) {\n"
"                    avgFrameTimeEl.innerText = avgTime.toFixed(1) + ' ms';\n"
"                }\n"
"            }\n"
"        }\n"
"        \n"
"        function updateMicLevel(level) {\n"
"            const levelPercent = Math.min(100, Math.floor(Math.abs(level) * 200));\n"
"            const micLevelSpan = document.getElementById('micLevel');\n"
"            if (levelPercent > 10) {\n"
"                micLevelSpan.innerHTML = ' Level: ' + '-'.repeat(Math.floor(levelPercent / 10)) + ' '.repeat(10 - Math.floor(levelPercent / 10));\n"
"            } else {\n"
"                micLevelSpan.innerHTML = ' Level: ░░░░░░░░░░';\n"
"            }\n"
"        }\n"
"        \n"
"        function setupAudio() {\n"
"            if (audioContext) {\n"
"                addMessage('Audio already initialized', 'info');\n"
"                return;\n"
"            }\n"
"            \n"
"            addMessage('Requesting microphone access...', 'info');\n"
"            \n"
"            navigator.mediaDevices.getUserMedia({ audio: {\n"
"                channelCount: 1,\n"
"                sampleRate: AUDIO_CONFIG.sampleRate,\n"
"                echoCancellation: true,\n"
"                noiseSuppression: true,\n"
"                autoGainControl: true\n"
"            }})\n"
"            .then(stream => {\n"
"                mediaStream = stream;\n"
"                audioContext = new AudioContext({ sampleRate: AUDIO_CONFIG.sampleRate });\n"
"                \n"
"                const source = audioContext.createMediaStreamSource(stream);\n"
"                scriptProcessor = audioContext.createScriptProcessor(4096, 1, 1);\n"
"                \n"
"                let lastSendTime = 0;\n"
"                const minSendInterval = AUDIO_CONFIG.frameDurationMs;\n"
"                let frameStartTime = 0;\n"
"                \n"
"                scriptProcessor.onaudioprocess = (event) => {\n"
"                    const inputData = event.inputBuffer.getChannelData(0);\n"
"                    \n"
"                    let peak = 0;\n"
"                    for (let i = 0; i < inputData.length; i++) {\n"
"                        const sample = Math.max(-1, Math.min(1, inputData[i]));\n"
"                        if (Math.abs(sample) > peak) {\n"
"                            peak = Math.abs(sample);\n"
"                        }\n"
"                        pendingSamples.push(sample);\n"
"                    }\n"
"                    updateMicLevel(peak);\n"
"\n"
"                    while (pendingSamples.length >= AUDIO_CONFIG.samplesPerFrame) {\n"
"                        if (!ws || ws.readyState !== WebSocket.OPEN || isMuted) {\n"
"                            pendingSamples = [];\n"
"                            break;\n"
"                        }\n"
"\n"
"                        const frameData = pendingSamples.splice(0, AUDIO_CONFIG.samplesPerFrame);\n"
"                        const sampleArray = new Int16Array(AUDIO_CONFIG.samplesPerFrame);\n"
"                        for (let i = 0; i < AUDIO_CONFIG.samplesPerFrame; i++) {\n"
"                            sampleArray[i] = Math.floor(frameData[i] * 32767);\n"
"                        }\n"
"\n"
"                        const now = performance.now();\n"
"                        if (frameStartTime > 0) {\n"
"                            const frameTime = now - frameStartTime;\n"
"                            totalFrameTime += frameTime;\n"
"                            frameCount++;\n"
"                            updateFramesSent();\n"
"                        }\n"
"                        frameStartTime = now;\n"
"\n"
"                        const packet = {\n"
"                            type: 'audio',\n"
"                            samples: Array.from(sampleArray),\n"
"                            timestamp: ntp.getServerTime()\n"
"                        };\n"
"\n"
"                        ws.send(JSON.stringify(packet));\n"
"                    }\n"
"                };\n"
"                \n"
"                source.connect(scriptProcessor);\n"
"                scriptProcessor.connect(audioContext.destination);\n"
"                \n"
"                addMessage('Microphone active at ' + audioContext.sampleRate + 'Hz | Frame: ' + AUDIO_CONFIG.frameDurationMs + 'ms', 'success');\n"
"                document.getElementById('audioStatus').innerHTML = ' Audio: Live';\n"
"            })\n"
"            .catch(err => {\n"
"                addMessage('Microphone error: ' + err.message, 'error');\n"
"                console.error('Microphone error:', err);\n"
"            });\n"
"        }\n"
"        \n"
"        function closeAudio() {\n"
"            isPlaying = false;\n"
"            jitterQueue = [];\n"
"            if (scriptProcessor) {\n"
"                scriptProcessor.disconnect();\n"
"                scriptProcessor = null;\n"
"            }\n"
"            if (audioContext) {\n"
"                audioContext.close();\n"
"                audioContext = null;\n"
"            }\n"
"            if (mediaStream) {\n"
"                mediaStream.getTracks().forEach(track => track.stop());\n"
"                mediaStream = null;\n"
"            }\n"
"            frameCount = 0;\n"
"            totalFrameTime = 0;\n"
"            framesReceived = 0;\n"
"            pendingSamples = [];\n"
"            updateFramesSent();\n"
"            document.getElementById('framesReceived').innerText = '0';\n"
"            document.getElementById('audioStatus').innerHTML = ' Audio: Stopped';\n"
"            document.getElementById('micLevel').innerHTML = '';\n"
"            addMessage('Audio closed', 'info');\n"
"        }\n"
"        \n"
"        function toggleMute() {\n"
"            isMuted = !isMuted;\n"
"            const btn = document.getElementById('muteBtn');\n"
"            btn.innerHTML = isMuted ? ' Unmute' : ' Mute';\n"
"            if(isMuted) {\n"
"                btn.classList.add('active');\n"
"            } else {\n"
"                btn.classList.remove('active');\n"
"            }\n"
"            document.getElementById('audioStatus').innerHTML = isMuted ? ' Audio: Muted' : ' Audio: Live';\n"
"            addMessage(isMuted ? 'Microphone muted' : 'Microphone unmuted', 'info');\n"
"        }\n"
"        \n"
"        async function joinRoom() {\n"
"            const roomId = document.getElementById('roomId').value.trim();\n"
"            if (!roomId) {\n"
"                addMessage('Please enter a room ID', 'error');\n"
"                return;\n"
"            }\n"
"            \n"
"            if (ws && ws.readyState === WebSocket.OPEN) {\n"
"                addMessage('Already connected to room: ' + currentRoom, 'error');\n"
"                return;\n"
"            }\n"
"            \n"
"            if (ntp.offset === 0) {\n"
"                addMessage('Syncing time with server...', 'info');\n"
"                await ntp.sync();\n"
"            }\n"
"            \n"
"            currentRoom = roomId;\n"
"            isExplicitClose = false;\n"
"            \n"
"            const wsProtocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
"            const wsHost = window.location.host || 'localhost:8080';\n"
"            const wsUrl = wsProtocol + '//' + wsHost + '/ws?room=' + encodeURIComponent(roomId);\n"
"            \n"
"            addMessage('Connecting to room: ' + roomId + '...', 'info');\n"
"            document.getElementById('connectionStatus').innerHTML = ' Connecting to ' + roomId + '...';\n"
"            \n"
"            try {\n"
"                ws = new WebSocket(wsUrl);\n"
"                \n"
"                ws.onopen = () => {\n"
"                    document.getElementById('connectionStatus').innerHTML = ' Connected to ' + roomId;\n"
"                    addMessage('Joined room: ' + roomId, 'success');\n"
"                    setupAudio();\n"
"                };\n"
"                \n"
"                ws.onmessage = (event) => {\n"
"                    try {\n"
"                        const data = JSON.parse(event.data);\n"
"                        if (data.type === 'system') {\n"
"                            addMessage('System: ' + data.message, 'info');\n"
"                        } else if (data.type === 'message') {\n"
"                            addMessage((data.from || 'User') + ': ' + data.text, 'info');\n"
"                        } else if (data.type === 'audio') {\n"
"                            if (data.samples && data.samples.length > 0) {\n"
"                                addToJitterBuffer(data.samples);\n"
"                            }\n"
"                        }\n"
"                    } catch (e) {\n"
"                        console.log('Non-JSON message:', event.data.substring(0, 100));\n"
"                    }\n"
"                };\n"
"                \n"
"                ws.onclose = () => {\n"
"                    document.getElementById('connectionStatus').innerHTML = 'Disconnected';\n"
"                    addMessage(isExplicitClose ? 'Left room: ' + currentRoom : 'Disconnected from ' + currentRoom, 'error');\n"
"                    closeAudio();\n"
"                    ws = null;\n"
"                    currentRoom = null;\n"
"                };\n"
"                \n"
"                ws.onerror = (error) => {\n"
"                    console.error('WebSocket error:', error);\n"
"                    addMessage('WebSocket connection error', 'error');\n"
"                    document.getElementById('connectionStatus').innerHTML = ' Connection error';\n"
"                };\n"
"                \n"
"            } catch (err) {\n"
"                addMessage('Failed to connect: ' + err.message, 'error');\n"
"                document.getElementById('connectionStatus').innerHTML = ' Connection failed';\n"
"            }\n"
"        }\n"
"        \n"
"        function leaveRoom() {\n"
"            if (!ws) {\n"
"                addMessage('Not connected to any room', 'error');\n"
"                return;\n"
"            }\n"
"            isExplicitClose = true;\n"
"            addMessage('Leaving room: ' + currentRoom, 'info');\n"
"            ws.close();\n"
"        }\n"
"        \n"
"        async function init() {\n"
"            addMessage('Speeqr Audio Conference - Day 2', 'success');\n"
"            addMessage('Audio config: ' + (AUDIO_CONFIG.sampleRate/1000) + 'kHz, ' + AUDIO_CONFIG.frameDurationMs + 'ms frames', 'info');\n"
"            addMessage('Jitter buffer enabled: 100ms target', 'info');\n"
"            await ntp.sync();\n"
"            \n"
"            setInterval(async () => {\n"
"                if (ws && ws.readyState === WebSocket.OPEN) {\n"
"                    await ntp.sync();\n"
"                }\n"
"            }, 30000);\n"
"        }\n"
"        \n"
"        init();\n"
"        </script>\n"
        "</body>\n"
        "</html>\n"
    );
}

void handle_http_request(tcp::socket& socket, const http::request<http::string_body>& req) {
    std::cout << "[HTTP] " << req.method() << " " << req.target() << std::endl;
    
    http::response<http::string_body> res;
    
    if (req.method() == http::verb::get && 
        (req.target() == "/" || req.target() == "/index.html" || req.target().empty())) {
        
        std::string html = get_html();
        res.result(http::status::ok);
        res.set(http::field::content_type, "text/html; charset=utf-8");
        res.set(http::field::server, "Speeqr/1.0");
        res.body() = html;
        res.content_length(html.size());
        res.keep_alive(false);
        
        std::cout << "[HTTP] Serving HTML page (" << html.size() << " bytes)" << std::endl;
    }
    else if (req.method() == http::verb::get && req.target() == "/time") {
        auto now = std::chrono::steady_clock::now();
        auto timestamp = std::chrono::duration<double, std::milli>(now.time_since_epoch()).count();
        
        std::stringstream json;
        json << std::fixed << std::setprecision(3);
        json << "{\"timestamp\": " << timestamp << "}";
        std::string body = json.str();
        
        res.result(http::status::ok);
        res.set(http::field::content_type, "application/json");
        res.set(http::field::server, "Speeqr/1.0");
        res.body() = body;
        res.content_length(body.size());
        res.keep_alive(false);
        
        std::cout << "[HTTP] Time sync response: " << body << std::endl;
    }
    else {
        res.result(http::status::not_found);
        res.set(http::field::content_type, "text/plain");
        res.body() = "404 Not Found\n\nAvailable endpoints:\n- GET /\n- GET /time\n- WS /ws?room=ROOM_ID";
        res.content_length(res.body().size());
        res.keep_alive(false);
        
        std::cout << "[HTTP] 404 Not Found for: " << req.target() << std::endl;
    }
    
    boost::system::error_code ec;
    http::write(socket, res, ec);
    if (ec) {
        std::cerr << "[HTTP] Write error: " << ec.message() << std::endl;
    }
}
